### PR TITLE
Added version 6 for symfony/process to the required versions

### PR DESCRIPTION
**Pull request by rkaldung**
This pull requests fixes https://github.com/maschmann/php-ansible/issues/73 since I also discovered this in a project I'm working on.
All tests passed with symfony/process 6.0.3

### CODE REVIEW

**Comment by maschmann** [comment]
Hi @rkaldung, I'll check your changes (and try to fix or drop scrutinizer) - Tried it myself on Friday and tests passing, so it seems OK. Maybe ^4.0 can be dropped, too ;-)

**Comment by rkaldung** [comment]
> // edit: Can you please change the PR to develop as target? mainline is only for fixes & releases :-)

Hi @maschmann, 
Sure, should I remove ^4.0 too?

**Comment by maschmann** [comment]
Ah, damn. I already removed it. 
As you can see, there's a difference between main and dev. But this will be the next release.

**Comment by rkaldung** [comment]
> Ah, damn. I already removed it. As you can see, there's a difference between main and dev. But this will be the next release.

You want me to give it a try to solve the conflict or should I take my hands off?

**Comment by maschmann** [comment]
if you also change the source of the PR to develop, too, it should be a piece of cake - you just changed composer stuff.

**Comment by rkaldung** [comment]
> if you also change the source of the PR to develop, too, it should be a piece of cake - you just changed composer stuff. // I'll have to add new travis versions, too - will have time for that tonight, so you can expect a version bump with your changes by tomorrow, I guess :-)

Sounds good, since I can't change my branch of the PR I'll create a new onw.

**Pull request closed without merging**
