### PR TITLE
Make process available via getter

### LINKED ISSUE #90: When using `json()` failing command has output on stdout and not stderr
When the option `json()` is turned on, a not successful execution has its output in on `stdout` and not on `stderr`. 

I am not sure whats the best way to get around the issue, that a failing execution does not output anything

Option 1:
Check in `runProcess` if the `ANSIBLE_STDOUT_CALLBACK` is set to `json` and then return `$process->getOutput()` instead of `$process->getErrorOutput()`.

Option 2:
Make the process accesible from the outside and make the user responsible to get the right output

Option 3:
just always return `$process->getOutput()` (don't know how it's without `json` enabled)

### PR DESCRIPTION
**Pull request by bambamboole**
Fixes #90 by exposing the process via a stateful getter which gets reset on `runProcess`

### CODE REVIEW

**Comment by maschmann** [comment]
This PR introduces two changes. the return to sprintf'ing the hosts and also an exposed getter for symfony process.
I'd prefer to keep the process hidden within the wrappers and fixing the STDOUT issue from #90 in another way (see comment).
The host sprintf I'd gladly accept :-)

**Comment by bambamboole** [comment]
let me update the PR :)

**Comment by bambamboole** [comment]
AH I think the stuff was in the other PR. let me close this for now. Looking forward to the new release.

**Comment by maschmann** [comment]
You had both changes within this one, I guess (https://github.com/maschmann/php-ansible/pull/91/commits/757b22619e42c3d2507e4a947148907e4a507b9d)

**Pull request closed without merging**
